version: '3.8'

services:
  gemma-api:
    build: .
    image: gemma-api:latest
    container_name: gemma-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface